-- Seed exercises with aliases and muscles
-- This script inserts all 100 exercises from clean_exercises_json.json

BEGIN;

-- Temporary table to store exercise IDs for reference
CREATE TEMP TABLE temp_exercise_ids (
  temp_name text PRIMARY KEY,
  exercise_id uuid
);

-- Insert all exercises and capture their IDs
INSERT INTO exercises (name, category, difficulty_level, equipment, is_public, is_custom, source)
VALUES
  ('Barbell Bench Press', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Dumbbell Bench Press', 'strength', 'intermediate', 'dumbbell', true, false, 'official'),
  ('Incline Barbell Bench Press', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Incline Dumbbell Press', 'strength', 'intermediate', 'dumbbell', true, false, 'official'),
  ('Decline Bench Press', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Push-Up', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Chest Fly Machine', 'strength', 'beginner', 'machine', true, false, 'official'),
  ('Dumbbell Chest Fly', 'strength', 'intermediate', 'dumbbell', true, false, 'official'),
  ('Cable Chest Fly', 'strength', 'intermediate', 'cable', true, false, 'official'),
  ('Close-Grip Bench Press', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Weighted Push-Up', 'strength', 'advanced', 'bodyweight', true, false, 'official'),
  ('Smith Machine Bench Press', 'strength', 'beginner', 'machine', true, false, 'official'),
  ('Floor Press', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Resistance Band Chest Press', 'strength', 'beginner', 'band', true, false, 'official'),
  ('Conventional Deadlift', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Bent-Over Barbell Row', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('One-Arm Dumbbell Row', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Seated Cable Row', 'strength', 'beginner', 'cable', true, false, 'official'),
  ('Lat Pulldown', 'strength', 'beginner', 'cable', true, false, 'official'),
  ('Pull-Up', 'strength', 'advanced', 'bodyweight', true, false, 'official'),
  ('Chin-Up', 'strength', 'advanced', 'bodyweight', true, false, 'official'),
  ('T-Bar Row', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Chest-Supported Dumbbell Row', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Straight Arm Pulldown', 'strength', 'beginner', 'cable', true, false, 'official'),
  ('Inverted Row', 'strength', 'intermediate', 'bodyweight', true, false, 'official'),
  ('Machine Row', 'strength', 'beginner', 'machine', true, false, 'official'),
  ('Good Morning', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Back Extension', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Rack Pull', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Barbell Overhead Press', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Dumbbell Shoulder Press', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Arnold Press', 'strength', 'intermediate', 'dumbbell', true, false, 'official'),
  ('Lateral Raise', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Cable Lateral Raise', 'strength', 'intermediate', 'cable', true, false, 'official'),
  ('Front Raise', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Rear Delt Fly', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Face Pull', 'strength', 'beginner', 'cable', true, false, 'official'),
  ('Upright Row', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Machine Shoulder Press', 'strength', 'beginner', 'machine', true, false, 'official'),
  ('Cable Front Raise', 'strength', 'beginner', 'cable', true, false, 'official'),
  ('Barbell Push Press', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Barbell Biceps Curl', 'strength', 'beginner', 'barbell', true, false, 'official'),
  ('Dumbbell Biceps Curl', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Hammer Curl', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Preacher Curl', 'strength', 'intermediate', 'machine', true, false, 'official'),
  ('Cable Biceps Curl', 'strength', 'beginner', 'cable', true, false, 'official'),
  ('Triceps Pushdown', 'strength', 'beginner', 'cable', true, false, 'official'),
  ('Overhead Triceps Extension', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Skullcrusher', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Dips', 'strength', 'advanced', 'bodyweight', true, false, 'official'),
  ('Concentration Curl', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Cable Triceps Kickback', 'strength', 'beginner', 'cable', true, false, 'official'),
  ('Back Squat', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Front Squat', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Goblet Squat', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Leg Press', 'strength', 'beginner', 'machine', true, false, 'official'),
  ('Romanian Deadlift', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Stiff-Leg Deadlift', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Lying Leg Curl', 'strength', 'beginner', 'machine', true, false, 'official'),
  ('Seated Leg Curl', 'strength', 'beginner', 'machine', true, false, 'official'),
  ('Walking Lunge', 'strength', 'intermediate', 'bodyweight', true, false, 'official'),
  ('Bulgarian Split Squat', 'strength', 'advanced', 'bodyweight', true, false, 'official'),
  ('Step-Up', 'strength', 'beginner', 'dumbbell', true, false, 'official'),
  ('Hip Thrust', 'strength', 'intermediate', 'barbell', true, false, 'official'),
  ('Glute Bridge', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Standing Calf Raise', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Seated Calf Raise', 'strength', 'beginner', 'machine', true, false, 'official'),
  ('Hack Squat', 'strength', 'intermediate', 'machine', true, false, 'official'),
  ('Sumo Deadlift', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Single-Leg Romanian Deadlift', 'strength', 'advanced', 'dumbbell', true, false, 'official'),
  ('Leg Extension', 'strength', 'beginner', 'machine', true, false, 'official'),
  ('Reverse Lunge', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Plank', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Side Plank', 'strength', 'intermediate', 'bodyweight', true, false, 'official'),
  ('Crunch', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Bicycle Crunch', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Hanging Leg Raise', 'strength', 'advanced', 'bodyweight', true, false, 'official'),
  ('Lying Leg Raise', 'strength', 'intermediate', 'bodyweight', true, false, 'official'),
  ('Russian Twist', 'strength', 'intermediate', 'bodyweight', true, false, 'official'),
  ('Cable Crunch', 'strength', 'intermediate', 'cable', true, false, 'official'),
  ('Ab Wheel Rollout', 'strength', 'advanced', 'bodyweight', true, false, 'official'),
  ('Dead Bug', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Bird Dog', 'strength', 'beginner', 'bodyweight', true, false, 'official'),
  ('Back Extension Hold', 'strength', 'intermediate', 'bodyweight', true, false, 'official'),
  ('Running', 'cardio', 'beginner', 'bodyweight', true, false, 'official'),
  ('Cycling', 'cardio', 'beginner', 'machine', true, false, 'official'),
  ('Rowing', 'cardio', 'intermediate', 'machine', true, false, 'official'),
  ('Elliptical Trainer', 'cardio', 'beginner', 'machine', true, false, 'official'),
  ('Jump Rope', 'cardio', 'intermediate', 'bodyweight', true, false, 'official'),
  ('Stair Climber', 'cardio', 'intermediate', 'machine', true, false, 'official'),
  ('High Knees', 'cardio', 'beginner', 'bodyweight', true, false, 'official'),
  ('Burpees', 'cardio', 'advanced', 'bodyweight', true, false, 'official'),
  ('Mountain Climbers', 'cardio', 'intermediate', 'bodyweight', true, false, 'official'),
  ('Assault Bike', 'cardio', 'advanced', 'machine', true, false, 'official'),
  ('World''s Greatest Stretch', 'mobility', 'beginner', 'bodyweight', true, false, 'official'),
  ('Hip Flexor Stretch', 'mobility', 'beginner', 'bodyweight', true, false, 'official'),
  ('90-90 Hip Rotation', 'mobility', 'beginner', 'bodyweight', true, false, 'official'),
  ('Thoracic Spine Rotation', 'mobility', 'beginner', 'bodyweight', true, false, 'official'),
  ('Cat-Cow Stretch', 'mobility', 'beginner', 'bodyweight', true, false, 'official'),
  ('Ankle Dorsiflexion Drill', 'mobility', 'beginner', 'bodyweight', true, false, 'official'),
  ('Shoulder Dislocates', 'mobility', 'beginner', 'band', true, false, 'official'),
  ('Deep Squat Hold', 'mobility', 'beginner', 'bodyweight', true, false, 'official'),
  ('Power Clean', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Clean and Jerk', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Snatch', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Thruster', 'strength', 'advanced', 'barbell', true, false, 'official'),
  ('Kettlebell Swing', 'strength', 'intermediate', 'kettlebell', true, false, 'official'),
  ('Man Maker', 'strength', 'advanced', 'dumbbell', true, false, 'official'),
  ('Farmer''s Carry', 'strength', 'intermediate', 'dumbbell', true, false, 'official'),
  ('Bear Crawl', 'strength', 'intermediate', 'bodyweight', true, false, 'official'),
  ('Wall Ball', 'strength', 'intermediate', 'medicine ball', true, false, 'official'),
  ('Sandbag Clean', 'strength', 'advanced', 'other', true, false, 'official')
RETURNING name, id INTO temp_exercise_ids;

COMMIT;

-- Verify the insert
SELECT COUNT(*) as total_exercises FROM exercises WHERE is_public = true;
